src/app.ts

- Disable proxy checkout functions
The goal of this PR is to disable proxy to checkout function and set a mock response for `browsers/current/info`.

Disable proxy checkout functions

---

package.json
src/app.ts

- add mock happy path for 
- `GET /checkout/ecommerce/v1/carts/:id`
- `GET /checkout/ecommerce/v1/payment-requests/:rptid`
- `GET /checkout/ecommerce/v1/payment-methods`

feat: add ecommerce api

---

src/app.ts

Added error case handling in the payment-request/:rptid endpoint.
Error case handling has been added in the payment-request/:rptid endpoint to allow the FE checkout to perform, during execution of the code review pipeline, integration tests simulating those performed in the pagopa-checkout-test project in DEV and UAT.
The tests were performed locally.

CHK-925 added fault cases for verify method

---

README.md
package.json
src/app.ts
src/handlers/pgs.ts
src/utils/xpay.ts
yarn.lock

- Add `payment-transaction-gateway` mock for `auth-response-xpay` polling endpoint
- Add success case (transactionId starting with 0)
- Add not found case (otherwise)
- FE development

[CHK-929] feat: add pgs xpay auth mock

---

package.json
src/app.ts
src/flow.ts
src/handlers/transactions.ts
src/utils/3ds2.ts

Add nodo take in charge simulation by input rpt id with notice code starting by 30202
This mock response is required in order to test Nodo take in charge response with Checkout front end

Add nodo timeout configuration

---

README.md
src/flow.ts
src/handlers/pgs.ts
src/utils/xpay.ts

- Add new mock case for xpay pgs authorization endpoint
- FE test on multi attempt delayed response
| Case                        | Code                                  |
|-----------------------------|---------------------------------------|
| Success                     | 0XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX  |
| (NEW) Success (2 retry attempt)   | 01XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX  |
| Not found                   | XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX  |

[CHK-929] feat: xpay pgs delayed polling endpoint

---

README.md

Update README to reflect the mockFlow cookie enumerations
Update documentation to the last modifications
N.A.

feat: update readme to mockFlow enumerations

---

src/handlers/pgs.ts

- fix: wrong function handler definition error

fix: handler function error - xpay auth

---

README.md
package.json
src/app.ts
src/flow.ts
src/handlers/pgs.ts
src/index.ts
src/utils/vpos.ts
src/utils/xpay.ts

Add  Vpos authorization polling endpoint /request-payments/vpos mock logic that handles VPOS authorization requests steps
This mock requests are needed in order to perform transaction-gateway-fe local and pipeline tests
Postman API invocations

feat: add vpos flow mock

---

src/handlers/pgs.ts

Changed VPOS clientReturnUrl 
Changed return url to google.com as it is needed for performing integration tests checks

fix: changed return url

---

package.json
src/utils/ecommerce/activation.ts
src/utils/ecommerce/transaction.ts

Changed name of the pagopa-infra branch to remove the field **amountTotal** 
Has been updated the package.json file in particular the name of the infra branch for the generation of ecommerce source code to eliminate the use of the amountTotal field.
The tests were performed locally.

Fix : openapi ecommerce and removed amountTotal

---

package.json
src/utils/ecommerce/transaction.ts

Changed response **status** into GET transaction
Changed response **status** into GET transaction to fix problem into FE integration test
Modified *status** response in GET transaction to resolve issue in FE integration tests
The tests were performed locally.

fix: changed status of transaction into GET transaction

---

src/app.ts
src/handlers/ecommerce/verify.ts
src/utils/ecommerce/transaction.ts
src/utils/ecommerce/verify.ts

Modified mock to perform payment verification.
The method for performing verification of a payment has been changed. 
In particular, the ecommerce openapi specification was used to construct the responses.
The tests were performed locally.

CHK-1021-verify-method

---

README.md
package.json
src/flow.ts
src/handlers/ecommerce/activation.ts
src/utils/ecommerce/activation.ts

During the activation phase, management of suffixes on the RPTID was added to generate transactionId useful for payment execution **xpay** and **vpos**.
During the activation phase, suffix handling was added on the RPTID to generate transactionIds in response that respect the syntax useful for activating call controls:
**- GET /request-payments/xpay/:requestId**
**- GET /request-payments/vpos/:requestId**
Tests were carried out locally.
I test so

CHK-1022-transactionId-for-xpay-vpos

---

src/app.ts

Modified api path for vpos and xpay mocks.
Changed the path of the api for the xpay and vpos mock in particular : 
-    **OLD GET XPAY   /request-payments/xpay/:requestId**
-    **NEW GET XPAY  /payment-transactions-gateway/external/v1/request-payments/xpay/:requestId**
-    **OLD GET VPOS  /request-payments/vpos/:requestId**
-    **NEW GET VPOS  /payment-transactions-gateway/external/v1/request-payments/vpos/:requestId**

fix-vpos-xpay-api-context

---

package.json
src/app.ts
src/utils/ecommerce/auth-request.ts
yarn.lock

Added new ecommerce basepath since checkout call the new group of the api
change the path of ecommerce api calls
This is done to refer to our own domain in infra
Test were performed locally

[CHK-1108] new base path for ecommerce

---

README.md
src/app.ts
src/flow.ts
src/handlers/ecommerce/activation.ts
src/handlers/ecommerce/transaction.ts
src/utils/ecommerce/transaction.ts

Added new api to perform transaction cancellation.
-  **DELETE transactions/transactionId**
The api handles various flow cases based on the suffix of the RPTID used for activation.
Added mock of new api to perform transaction cancellation useful for unlocking payment

CHK-1260-added-delete-transaction-mock

---

src/handlers/ecommerce/transaction.ts

Fix http status for DELETE transaction method
Changed the DELETE response code from 404 to 500.

fix return http status

---

src/utils/ecommerce/transaction.ts

Changed response status of GET transaction from NOTIFIED to NOTIFIED_OK.

Changed status NOTIFIED to NOTIFIED_OK

---

src/utils/ecommerce/payment-method.ts

Depends on: https://github.com/pagopa/pagopa-infra/pull/830
Update payment methods response to the updated api
This modification is needed in order to update payment methods response
Local test with checkout f.e.

fix: update method response

---

package.json
src/app.ts
src/utils/ecommerce/activation.ts
src/utils/ecommerce/transaction.ts

Update mock to fit new activateV2 invocation

[CHK-1347] update activate and get transaction

---

src/app.ts
src/utils/ecommerce/cart.ts

Added in the body of the GET cart response the reference of the new field idCart.
Also changed the path of the api.
The change was made to allow testing of the change related to idCart.
The tests were performed locally

CHK-1405-added-idCart-into-get-method

---

src/utils/ecommerce/activation.ts
src/utils/ecommerce/cart.ts

1. Change get carts mocked response to return 5 distinct payment notices (with different amounts)
2. Fix post transaction response build: response payment notice list is now build filling additional informations to the input received payment notice list.
Those modifications are needed to test carts with multiple payment notices
Local test with checkout f.e.

fix: change CARTS response adding multiple payment notices

---

src/handlers/ecommerce/activation.ts
src/utils/ecommerce/activation.ts

Add checking about captcha value present in post transaction
Add check for captcha not null in activation mock
Since captcha has been added to post transaction, it will be check in mock. A generic error will be displayed
Test were performed locally

[CHK-1493] add captcha check in post transaction

---

src/handlers/ecommerce/psp.ts

Depends on https://github.com/pagopa/pagopa-infra/pull/988
Added check for **x-transaction-id** header into **/ecommerce/checkout/v1/payment-methods/:id/fees**
The change was made to handle checking for the presence of the **x-transaction-id** header when searching for psps.

CHK-1564-x-transaction-id

---

README.md
src/flow.ts
src/handlers/ecommerce/activation.ts
src/handlers/ecommerce/transaction.ts

Added a FlowCase to simulate sendPaymentResult not receiving.
With the suffix 73 on the rptId we will be able to pilot the final state to CLOSED returned by the GET transaction.
The activity was made to allow for a new test case on FE.

feat(CLOSED flow): added flowCase to simulate no sendPaymentResult receiving

---

package.json
src/utils/ecommerce/activation.ts
src/utils/ecommerce/transaction.ts

Update infra and data refs to make mock working
Update package
Add allCCP flag where needed

[CHK-1630] add allCCP flag to payment info and rquest auth request body

---

package.json
src/handlers/ecommerce/transaction.ts

Fix get transaction for flowCase CLOSED. Added into response the sendPaymentResultOutcome NOT_RECEIVED

fix:added into get transaction for status closed the new sendPaymentOutcome

---

src/utils/ecommerce/psp.ts

Depends on https://github.com/pagopa/pagopa-infra/pull/1156
Add payment method description
Add payment method description

fix(calculate-fee): add payment method description

---

README.md
package.json
src/app.ts
src/handlers/ecommerce/payment-method.ts
src/handlers/payments.ts
src/handlers/wallet.ts
src/utils/ecommerce/payment-method.ts
src/utils/npg-api.yaml
yarn.lock

Chk-1808 create mock npg

---

src/handlers/ecommerce/payment-method.ts

Add sessionId passed as url param to the SessionPaymentMethodResponse
add sessionId to the response body
Tests were performed locally

[CHK-1825] add sessionId to SessionPaymentMethodResponse

---

src/handlers/ecommerce/payment-method.ts

Added check for new header x-transaction-id-from-client into method
> GET /ecommerce/checkout/v1/payment-methods/:id/sessions/:idSession
The change was made to check the enhancement of the new header useful for checking the JWT.

feat(jwt): added check for x-transaction-id-from-client header

---

README.md
package.json
src/config.ts
src/handlers/ecommerce/payment-method.ts
src/index.ts
yarn.lock

* add typesafe config validation
* fix typo for env var `NPG_APY_KEY` -> `NPG_API_KEY`
* added `NPG_API_KEY` env var in README
Misc fixes + DX improvement

feat(config): add typesafe environment config validation

---

package.json
src/app.ts
src/flow.ts
src/handlers/ecommerce/auth-request.ts
src/handlers/ecommerce/payment-method.ts
src/utils/ecommerce/auth-request.ts

Adding emulate for confirm payment invoking nexi api for npg payment way

[CHK-1891] Fix mock npg to new orderId params

---

src/handlers/ecommerce/activation.ts
src/handlers/ecommerce/payment-method.ts
src/handlers/ecommerce/verify.ts

Add `recaptchaResponse` query param verifications for api protected by google Recaptcha
Add `recaptchaResponse` query param verifications for api protected by google Recaptcha
local test with postman

fix: add verification against recaptchaResponse

---

src/utils/ecommerce/payment-method.ts

This PR add a new payment method's list to the mock

[#CHK-2525] Add a new paymantmethods list

---

README.md
src/flow.ts
src/handlers/ecommerce/activation.ts
src/handlers/ecommerce/auth-request.ts
src/utils/ecommerce/auth-request.ts

Add mock case to navigate 5xx response code from ecommerce `authRequest`

add auth request 500 mock case

---

README.md
src/flow.ts
src/handlers/ecommerce/activation.ts
src/handlers/ecommerce/psp.ts
src/utils/ecommerce/psp.ts

Add function to mock 404 from get fees api

[CHK-3512] feat: add 404 getFees response

---

src/utils/ecommerce/psp.ts

fix: lint. diff string to avoid lint warning

---

README.md
src/flow.ts
src/handlers/ecommerce/activation.ts
src/utils/ecommerce/activation.ts

Add PPT_WISP_SESSIONE_SCONOSCIUTA error flow with **76** rptId suffix that simulate error during transaction activation.

[CHK-3536] feat: add PPT_WISP_SESSIONE_SCONOSCIUTA error flow

---

package.json

CHK-3498: restore infra tag for package json

---

src/app.ts

- changed path endpoint from "commerce" to "ecommerce" in v3/auth/transactions

fix: [CHK-3751] v3/auth/transactions

---

src/handlers/checkout-feature-flags.ts

- Updated api mock feature flag to return the new feature flag isPspPickerPageEnabled

feat: [CHK-3872] added isPspPickerPageEnabled as feature flag

---

src/handlers/checkout-feature-flags.ts

fix broken lint 
fix broken lint

fix: autolint

---

src/handlers/checkout-feature-flags.ts

- add new featureFlags isMaintenancePageEnabled

[PIDM-706-715-pagina-manutenzione] feat:  add new featureFlags isMaintenancePageEnabled

---

README.md
src/flow.ts
src/handlers/ecommerce/activation.ts
src/handlers/ecommerce/transaction.ts

feat:[CHK-4334] Implementation flow retray

---

src/handlers/ecommerce/payment-method.ts

- replaced return on getPaymentMethodsV4 function to fix generic error on authentication integration test suite
This fixes an unexpected error on `Should redirect to auth-expired page receiving 401 from get payment-methods` test from authentication suite on checkout-fe
- integration tests on authentication pass

fix: change v4 401 return
